/** @type {import('tailwindcss').Config} */
const rgb = (token) => `rgb(var(--color-${token}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: rgb("background"),
        canvas: rgb("canvas"),
        surface: rgb("surface"),
        "surface-dim": rgb("surface"),
        "surface-bright": rgb("surface-bright"),
        "surface-container-lowest": rgb("surface-container-lowest"),
        "surface-container-low": rgb("surface-container-low"),
        "surface-container": rgb("surface-container"),
        "surface-container-high": rgb("surface-container-high"),
        "surface-container-highest": rgb("surface-container-highest"),
        "surface-variant": rgb("surface-container-highest"),
        "on-surface": rgb("on-surface"),
        "on-surface-variant": rgb("on-surface-variant"),
        "on-background": rgb("on-surface"),
        outline: rgb("outline"),
        "outline-variant": rgb("outline-variant"),
        primary: rgb("primary"),
        "on-primary": rgb("on-primary"),
        "primary-container": rgb("primary-container"),
        "on-primary-container": rgb("on-primary-container"),
        "inverse-primary": rgb("inverse-primary"),
        "primary-fixed": rgb("primary-fixed"),
        secondary: rgb("secondary"),
        "secondary-container": rgb("secondary-container"),
        "on-secondary-container": rgb("on-secondary-container"),
        "secondary-fixed": rgb("secondary-fixed"),
        error: rgb("error"),
        "error-container": rgb("error-container"),
        "on-error": rgb("on-error"),
        card: rgb("card"),
        "card-foreground": rgb("on-surface"),
        muted: rgb("muted"),
        "muted-foreground": rgb("on-surface-variant"),
        border: rgb("outline-variant"),
        accent: rgb("primary-container"),
        "on-accent": rgb("on-primary-container"),
        destructive: rgb("error"),
        ring: rgb("ring"),
        foreground: rgb("on-surface"),
        scrim: rgb("scrim"),
        bid: rgb("bid"),
        ask: rgb("ask"),
        "obsidian-night": rgb("canvas"),
        "machined-graphite": rgb("card"),
      },
      borderColor: {
        DEFAULT: "rgb(var(--color-outline-variant) / 0.45)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        unit: "4px",
        "widget-gap": "16px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter Tight", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
        "data-md": ["JetBrains Mono", "ui-monospace", "monospace"],
        "body-md": ["Inter Tight", "system-ui", "sans-serif"],
        "body-lg": ["Inter Tight", "system-ui", "sans-serif"],
        "headline-sm": ["Inter Tight", "system-ui", "sans-serif"],
        "display-lg": ["Inter Tight", "system-ui", "sans-serif"],
        "data-lg": ["JetBrains Mono", "ui-monospace", "monospace"],
        "headline-md": ["Inter Tight", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "600" }],
        "data-md": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "data-lg": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-up": "fade-up 420ms cubic-bezier(0.16, 1, 0.3, 1) both",
      },
      zIndex: {
        nav: "40",
        overlay: "50",
        modal: "60",
      },
    },
  },
  plugins: [],
};
